version: "3.8"

services:
  # 🌍 MongoDB Service (Database)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # 🚀 API Gateway (First Entry Point)
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service
      - comment-service
      - team-service
      - notification-service

  # 👤 User Service
  user-service:
    build: ./user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    depends_on:
      - mongodb

  # ✅ Task Service
  task-service:
    build: ./task-service
    ports:
      - "${TASK_PORT}:${TASK_PORT}"
    depends_on:
      - mongodb

  # 💬 Comment Service
  comment-service:
    build: ./comment-service
    ports:
      - "${COMMENT_PORT}:${COMMENT_PORT}"
    depends_on:
      - mongodb

  # 👥 Team Service
  team-service:
    build: ./team-service
    ports:
      - "${TEAM_PORT}:${TEAM_PORT}"
    depends_on:
      - mongodb

  # 🔔 Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    depends_on:
      - mongodb

volumes:
  mongo_data:
